### ISSUE TITLE
v0.3.0 bump commit

### ISSUE THREAD

**Issue by willwhite** [mapbox/mapbox-file-sniff#24]
There is a v0.3.0 bump commit on the [v0.3.0 tag](https://github.com/mapbox/mapbox-file-sniff/releases/tag/v0.3.0) but not one on the master branch. @GretaCB can you push this?

**Comment by GretaCB** [comment]
All set: https://github.com/mapbox/mapbox-file-sniff/commit/84e8df7e4dcf89721c3571c3396dbd424089afb2
