### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by knutole** [mapbox/mapbox-file-sniff#27]
Problem with `.geojson` [file](http://bl.ocks.org/d/209985252f98b23d5081), the regex in `index.js:27` doesn't seem to match anything, and returns null instead of array. (`mapnik-omnivore : ^5.0.7`)

Error happens here:
```
   // check for topojson/geojson
    if (head.indexOf('\"type\":') !== -1){

        var m = /"type":\s?"(.+?)"/.exec(head);  // <= does not return array
        if (m[1] === 'Topology') return callback(null, 'topojson'); // <= error thrown
```

Error trace:
````
/var/www/wu/node_modules/mapnik-omnivore/node_modules/mapbox-file-sniff/index.js:28
        if (m[1] === 'Topology') return callback(null, 'topojson');
             ^
TypeError: Cannot read property '1' of null
    at sniff (/var/www/wu/node_modules/mapnik-omnivore/node_modules/mapbox-file-sniff/index.js:28:14)
    at /var/www/wu/node_modules/mapnik-omnivore/node_modules/mapbox-file-sniff/index.js:110:15
    at FSReqWrap.oncomplete (fs.js:95:15)
```


This could perhaps be due to something else - but the `.geojson` seems valid enough. Ideas?

**Comment by knutole** [comment]
Looked at it some more. It seems that the `head` (100 chars) contains this: 
` {"bbox: [151.1762091637833, -33.915824644189165, 151.2356068334641, -33.85847652573928], "type":"Feature`,

ie. `bbox` is before `type` in the geojson file. 

Tried `var head = buffer.toString().substring(0,200);`, and it seems to find the `m[1]` just fine. 

(Although I'm running into a new error, `Error creating Mapnik Datasource: GeoJSON Plugin: could not parse:`, but this may be unrelated.)

Not sure if it's invalid spec to have `bbox` first, but it seems to be the case in many of my random geojson files from the internets, so perhaps worth taking into consideration regardless of spec?

**Comment by sgillies** [comment]
JSON object items have no inherent order and GeoJSON adds no ordering constraints. GeoJSON processors should never be looking for "type" at the head of the file.

@GretaCB I made a [commit to mapnik-omnivore](https://github.com/mapbox/mapnik-omnivore/commit/7da2152728d6ef97f424e13a8a59e4f6e776a538#diff-168726dbe96b3ce427e7fedce31bb0bcL59) a while ago that addressed this kind of bug and maybe that needs to be done here as well.

**Comment by GretaCB** [comment]
Thanks for flagging @sgillies ! I will jump on this.

**Comment by GretaCB** [comment]
Hey @sgillies , took a closer look this morning. So the main reason mapbox-file-sniff checks for the `type` property is so it can validate between `geojson` and [`topojson`](https://github.com/mapbox/mapbox-file-sniff/blob/master/index.js#L28) (Check out https://github.com/mapbox/mapbox-file-sniff/issues/19). 

We could potentially increase the size of the header we use for detection. There's no guarantee where the type property will be, but this will decrease the odds of running into the array Type Error. 

Do you have any thoughts on how we can better detect geojson vs topojson?

**Comment by sgillies** [comment]
A TopoJSON object has 3 top-level items: `type, objects, arcs`. The first bytes of a TopoJSON text have to match one of these, and that's good for us because GeoJSON will have neither `objects` nor `arcs` nor `"type": "Topology"` in its initial bytes. What do you think about scanning the first N bytes (which I hesitate to call a header because there's no formal JSON header) for one of those three signatures?

**Comment by GretaCB** [comment]
PR at https://github.com/mapbox/mapbox-file-sniff/pull/28

**Comment by GretaCB** [comment]
`mapnik-omnivore` change merged. Closing since this solves the TypeError, but the file will bump into mapnik's json validation. See https://github.com/mapbox/mapbox-file-sniff/pull/28#issuecomment-97207583
