### ISSUE TITLE
Fails on node 5.0+

### ISSUE THREAD

**Issue by rclark** [mapbox/mapbox-file-sniff#43]
Breaking change from https://nodejs.org/en/blog/release/v5.0.0/

> zlib: Decompression now throws on truncated input (e.g. unexpected end of file)

Since we only pass part of the file through, [zlib.gunzip is always going to fail](https://github.com/mapbox/mapbox-file-sniff/blob/master/index.js#L79) meaning we can't detect tm2z or serialtiles files.

Unclear how we'll solve this when we push for node 6, I'm just recording the issue.

cc @ghoshkaj @GretaCB

**Comment by mapsam** [comment]
This was fixed by @springmeyer with the `{finishFlush: zlib.Z_SYNC_FLUSH}` option that allows for partial reads in node v6. Backwards compatibility was kept as well cbe9e32e5ad84777b01eddeab34fade9370697c9
