### ISSUE TITLE
Invalid Version

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-file-sniff#48]
Example: http://requirebin.com/?gist=bc69275e7018060b69f2de0740c3eae6

Introduced when going from 0.4.2 to 0.5.2

`node_modules/semver/semver.js:284 Uncaught TypeError: Invalid Version: undefined`

**Comment by mapsam** [comment]
Hey @drewbo - I'm not seeing the error in your example, it's just a `var sniff = require('mapbox-tile-copy')`. I'm unable to reproduce the error otherwise with a fresh `npm install mapbox-file-sniff`.

**Comment by drewbo** [comment]
@mapsam the error in the example throws in the console. Upon further investigation, I don't see it run requiring the package locally, only on requirebin and my bundled package (so probably related to browserify which both use?)

**Comment by drewbo** [comment]
Looks like `process.version` in browser environments is an empty string and this check fails: https://github.com/mapbox/mapbox-file-sniff/blob/master/index.js#L8
