### ISSUE TITLE
When dropping node v0.10.x support...

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-file-sniff#50]
Ticket to track that the shim added in https://github.com/mapbox/mapbox-file-sniff/commit/cbe9e32e5ad84777b01eddeab34fade9370697c9 and the patch against it in #49 should be removed when/if node v0.10.x support is dropped.

**Comment by mapsam** [comment]
I think we should drop 0.10.x support with #54!

**Comment by mapsam** [comment]
Node v0.10.x was dropped in https://github.com/mapbox/mapbox-file-sniff/pull/54 `1.0.0` and this shim was removed.
