### ISSUE TITLE
v0.5.4 release

### ISSUE THREAD

**Issue by springmeyer** [mapbox/mapbox-file-sniff#56]
Mainline is at v1.x now (https://github.com/mapbox/mapbox-file-sniff/blob/master/CHANGELOG.md#100) but many downstream apps will be slow to update due to the API change.

So I think we should publish a v0.5.4 release that is identical code to v0.5.3 but will serve the purpose of dropping the 25 MB file that ended up in the test data for the v0.5.3 release and it still going to be installed by deps that ask for `~0.5.3`:

```
$ npm install mapbox-file-sniff@0.5.x
npm WARN deprecated detect-geocsv@0.1.0: This module is now under the @mapbox namespace: install @mapbox/detect-geocsv instead
mapbox-file-sniff@0.5.3 node_modules/mapbox-file-sniff
├── semver@5.3.0
├── detect-geocsv@0.1.0
└── buffer@3.6.0 (ieee754@1.1.8, isarray@1.0.0, base64-js@0.0.8)

$ ls -lh node_modules/mapbox-file-sniff/test/data/ne_10m_admin_0_countries_lakes.geojson 
-rw-r--r-- 1 dane staff 25M Sep  1 15:08 node_modules/mapbox-file-sniff/test/data/ne_10m_admin_0_countries_lakes.geojson
```

**Comment by mapsam** [comment]
Good call @springmeyer 👍

**Comment by mapsam** [comment]
Resolved in https://github.com/mapbox/mapbox-file-sniff/pull/58
