### ISSUE TITLE
Check `isgeocsv` after checking for compressed file type 

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/mapbox-file-sniff#61]
In some very strange cases it seems that a compressed buffer can be recognized as a `csv` by `@mapbox/detect-geocsv` making `mapbox-file-sniff` return filetype ==`csv` instead of the expected `tif+gz`. 

### Fix / proposition : 
- check if the file is a `geocsv` at the end after testing if the file is a compressed type 

https://github.com/mapbox/mapbox-file-sniff/blob/f43d90d2c4139208f5974e036e65f3e92475330e/index.js#L112-L138

cc @GretaCB @mapsam @perrygeo

**Comment by GretaCB** [comment]
@vincentsarago Thanks for sharing your thoughts, I'm thinking similarly. This solution would require making sure we properly manage the [final `Unknown filetype` error](https://github.com/mapbox/mapbox-file-sniff/blob/f43d90d2c4139208f5974e036e65f3e92475330e/index.js#L131), in the case that none of the type checks spark a match.

My other thought is that reordering the logic feels somewhat like a patch, and not a full on solution. For example, the root question is why are some `tif+gz` files getting caught in detect-geocsv? Either there's a bug in creating the `tif+gz` or there's a bug in the buffer detection in `detect-geocsv`. In this case, mapbox-file-sniff is just stuck in the middle.

**Comment by vincentsarago** [comment]
> This solution would require making sure we properly manage the final Unknown filetype error, in the case that none of the type checks spark a match.

👌 

> My other thought is that reordering the logic feels somewhat like a patch, and not a full on solution. For example, the root question is why are some tif+gz files getting caught in detect-geocsv? Either there's a bug in creating the tif+gz or there's a bug in the buffer detection in detect-geocsv. In this case, mapbox-file-sniff is just stuck in the middle.

`detect-geocsv` is parsing a string buffer and look for particular string sequences: https://github.com/mapbox/detect-geocsv/blob/master/detect-geocsv.js#L59-L63

The main problem here, is that by running `detect-geocsv` on a gzip buffer we cannot guaranty it will not find the sequence it is looking for. It's not a bug in `detect-geocsv` itself, it's just we are using it on something it is not design for.
